# Generated by Django 4.2.3 on 2023-08-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ukm',
            options={'verbose_name': 'Small and Medium Enterprises', 'verbose_name_plural': 'Small and Medium Enterprises'},
        ),
        migrations.AddField(
            model_name='agenda',
            name='agenda_is_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenda',
            name='agenda_name_slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ukm',
            name='ukm_address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='ukm',
            name='ukm_description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ukm',
            name='ukm_image',
            field=models.ImageField(upload_to='images/ukm/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='ukm',
            name='ukm_legality',
            field=models.CharField(max_length=255, verbose_name='Legality'),
        ),
        migrations.AlterField(
            model_name='ukm',
            name='ukm_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ukm',
            name='ukm_number_phone',
            field=models.CharField(max_length=15, verbose_name='Number Phone'),
        ),
        migrations.AlterField(
            model_name='ukm',
            name='ukm_outlet',
            field=models.TextField(verbose_name='Outlet'),
        ),
        migrations.AlterField(
            model_name='ukm',
            name='ukm_owner',
            field=models.CharField(max_length=255, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='ukm',
            name='ukm_social_media',
            field=models.URLField(verbose_name='Social Media'),
        ),
        migrations.AlterField(
            model_name='ukm',
            name='ukm_types_product',
            field=models.CharField(max_length=255, verbose_name='Type of Product'),
        ),
        migrations.AlterField(
            model_name='ukm',
            name='ukm_website',
            field=models.URLField(verbose_name='Website'),
        ),
    ]
