# Generated by Django 4.2.3 on 2023-08-10 11:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_ukm_options_agenda_agenda_is_publish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantGroceries',
            fields=[
                ('groceries_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groceries_name', models.CharField(max_length=255, unique=True)),
                ('groceries_created', models.DateTimeField(auto_now_add=True)),
                ('groceries_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='agenda',
            name='agenda_is_publish',
            field=models.BooleanField(default=False, verbose_name='Is Publish'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='agenda_name_slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='UnitGroceries',
            fields=[
                ('unit_groceries_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_groceries_massa', models.CharField(max_length=64)),
                ('unit_groceries_price', models.PositiveIntegerField()),
                ('unit_groceries_quantity', models.PositiveSmallIntegerField()),
                ('unit_groceries_created', models.DateField()),
                ('unit_groceries_updated', models.DateTimeField(auto_now=True)),
                ('unit_groceries_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.variantgroceries')),
            ],
        ),
    ]
