# Generated by Django 4.2.3 on 2023-08-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_variantgroceries_alter_agenda_agenda_is_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ikm',
            name='ikm_name_slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ukm',
            name='ukm_name_slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
