# Generated by Django 4.2.3 on 2023-09-29 12:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_alter_ikm_options_alter_ukm_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenLPG',
            fields=[
                ('agen_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agen_name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('agen_slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
                ('agen_address', models.TextField(verbose_name='address')),
                ('agen_number_phone', models.CharField(max_length=15, verbose_name='Number Phone')),
                ('agen_base_name', models.CharField(max_length=255, unique=True, verbose_name='Base')),
                ('agen_base_address', models.TextField(verbose_name='Base address')),
                ('agen_image', models.ImageField(upload_to='images/agen/', verbose_name='Image')),
                ('agen_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('agen_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agen LPG',
                'verbose_name_plural': 'Agen LPG',
            },
        ),
        migrations.CreateModel(
            name='KiosPupuk',
            fields=[
                ('kios_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kios_name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('kios_address', models.TextField(verbose_name='address')),
                ('kios_slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
                ('kios_number_phone', models.CharField(max_length=15, verbose_name='Number Phone')),
                ('kios_distributor', models.CharField(max_length=255, unique=True, verbose_name='Distributor')),
                ('kios_distributor_address', models.TextField(verbose_name='address')),
                ('kios_image', models.ImageField(upload_to='images/kios/', verbose_name='Image')),
                ('kios_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('kios_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kios Pupuk',
                'verbose_name_plural': 'Kios Pupuk',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('market_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('market_name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('market_address', models.TextField(verbose_name='address')),
                ('market_slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
                ('market_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('market_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pasar',
                'verbose_name_plural': 'Pasar',
            },
        ),
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name': 'Agenda', 'verbose_name_plural': 'Agenda'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Dokumen', 'verbose_name_plural': 'Dokumen'},
        ),
        migrations.AlterModelOptions(
            name='unitgroceries',
            options={'verbose_name': 'Harga Bahan Pokok', 'verbose_name_plural': 'Harga Bahan Pokok'},
        ),
        migrations.AlterModelOptions(
            name='variantgroceries',
            options={'verbose_name': 'Nama Bahan Pokok', 'verbose_name_plural': 'Nama Bahan Pokok'},
        ),
        migrations.AlterField(
            model_name='document',
            name='document_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='unitgroceries',
            name='unit_groceries_created',
            field=models.DateField(verbose_name='Hari'),
        ),
        migrations.AlterField(
            model_name='unitgroceries',
            name='unit_groceries_massa',
            field=models.CharField(max_length=64, verbose_name='Satuan Bahan Pokok'),
        ),
        migrations.AlterField(
            model_name='unitgroceries',
            name='unit_groceries_price',
            field=models.PositiveIntegerField(verbose_name='Harga Bahan Pokok'),
        ),
        migrations.AlterField(
            model_name='unitgroceries',
            name='unit_groceries_quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Jumlah Bahan Pokok'),
        ),
        migrations.AlterField(
            model_name='unitgroceries',
            name='unit_groceries_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_groceries', to='administrator.variantgroceries', verbose_name='Nama Bahan Pokok'),
        ),
        migrations.AlterField(
            model_name='variantgroceries',
            name='groceries_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nama Bahan Pokok'),
        ),
    ]
