# Generated by Django 4.2.3 on 2023-09-30 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_agenlpg_kiospupuk_market_alter_agenda_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255, unique=True, verbose_name='Nama Barang')),
                ('item_slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
                ('item_market', models.CharField(max_length=255, verbose_name='Nama Pasar')),
                ('item_stock', models.PositiveIntegerField(verbose_name='Stok Awal')),
                ('item_income', models.PositiveIntegerField(verbose_name='Barang Masuk')),
                ('item_outcome', models.PositiveIntegerField(verbose_name='Penjualan')),
                ('item_last_stock', models.PositiveIntegerField(verbose_name='Stok Akhir')),
                ('item_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('item_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stok Barang',
                'verbose_name_plural': 'Stok Barang',
            },
        ),
        migrations.AlterField(
            model_name='agenlpg',
            name='agen_address',
            field=models.TextField(verbose_name='Alamat Agen'),
        ),
        migrations.AlterField(
            model_name='agenlpg',
            name='agen_base_address',
            field=models.TextField(verbose_name='Alamat Pangkalan'),
        ),
        migrations.AlterField(
            model_name='agenlpg',
            name='agen_base_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nama Pangkalan'),
        ),
        migrations.AlterField(
            model_name='agenlpg',
            name='agen_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nama Agen'),
        ),
        migrations.AlterField(
            model_name='agenlpg',
            name='agen_number_phone',
            field=models.CharField(max_length=15, verbose_name='Nomor Telepon'),
        ),
        migrations.AlterField(
            model_name='kiospupuk',
            name='kios_address',
            field=models.TextField(verbose_name='Alamat Kios'),
        ),
        migrations.AlterField(
            model_name='kiospupuk',
            name='kios_distributor',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nama Distributor'),
        ),
        migrations.AlterField(
            model_name='kiospupuk',
            name='kios_distributor_address',
            field=models.TextField(verbose_name='Alamat Distibutor'),
        ),
        migrations.AlterField(
            model_name='kiospupuk',
            name='kios_image',
            field=models.ImageField(upload_to='images/kios/', verbose_name='Gambar'),
        ),
        migrations.AlterField(
            model_name='kiospupuk',
            name='kios_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nama Kios'),
        ),
        migrations.AlterField(
            model_name='kiospupuk',
            name='kios_number_phone',
            field=models.CharField(max_length=15, verbose_name='Nomor Telepon'),
        ),
        migrations.AlterField(
            model_name='market',
            name='market_address',
            field=models.TextField(verbose_name='Alamat Pasar'),
        ),
        migrations.AlterField(
            model_name='market',
            name='market_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nama Pasar'),
        ),
    ]
