# Generated by Django 4.2.3 on 2023-09-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_stockitem_alter_agenlpg_agen_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='item_name',
            field=models.CharField(max_length=255, verbose_name='Nama Barang'),
        ),
    ]
