# Generated by Django 4.2.3 on 2023-10-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_alter_stockitem_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitgroceries',
            name='unit_groceries_massa',
        ),
        migrations.RemoveField(
            model_name='unitgroceries',
            name='unit_groceries_quantity',
        ),
        migrations.AddField(
            model_name='variantgroceries',
            name='groceries_massa',
            field=models.CharField(default='Kg', max_length=64, verbose_name='Satuan Bahan Pokok'),
        ),
        migrations.AddField(
            model_name='variantgroceries',
            name='groceries_quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Jumlah Bahan Pokok'),
        ),
        migrations.AlterField(
            model_name='agenlpg',
            name='agen_name',
            field=models.CharField(max_length=255, verbose_name='Nama Agen'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='item_last_stock',
            field=models.PositiveIntegerField(blank=True, verbose_name='Stok Akhir'),
        ),
    ]
