# Generated by Django 4.2.3 on 2023-10-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_remove_unitgroceries_unit_groceries_massa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantgroceries',
            name='groceries_quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Jumlah Bahan Pokok'),
        ),
    ]
